### ISSUE TITLE
Create gem

### ISSUE THREAD

**Issue by DoubleMalt** [olivertaylor/Textplay#23]
Almost missed it :)

**Comment by olivertaylor** [comment]
I've removed the old gem from rubygems.org. Github, for now, will be the one and only place to get textplay.

**Comment by DoubleMalt** [comment]
Why?

**Comment by olivertaylor** [comment]
I'm not very comfortable maintaining 2 separate distribution points for textplay. Mostly because I found keeping them both up to date arduous.
