### ISSUE TITLE
wrap_paragraphs not working?

### ISSUE THREAD

**Issue by RichardDooling** [olivertaylor/Textplay#34]
I noticed that the "wrap_paragraphs: on" switch wasn't doing its job for action or dialogue. I edited the textplay file directly and changed the default to wrap on, which fixed it. Then I noticed that dialogue was not set up to wrap? I deleted white-space: pre-wrap; and added white-space: #{wrap_paragraphs}; to the dialogue css and it works fine.

Is there a reason you did not want dialogue wrapping? Something I haven't thought of yet? I thought maybe it screwed up parentheticals but they look fine.

**Comment by olivertaylor** [comment]
Can you test against a file with this text? This works for me.

```
wrap_paragraphs: on

This is action
and another line of action

PERSON
This is something they say,
and another thing they say.

```

**Comment by RichardDooling** [comment]
I'm sorry about this. It must have just flaked out for a day. I just reran it with a fresh clone from Textplay and everything works fine. Apologies.
