### ISSUE TITLE
Change from PrinceXML to Weasyprint?

### ISSUE THREAD

**Issue by LaPingvino** [olivertaylor/Textplay#35]
I created an AUR package for Arch Linux of textplay and it looks like python-weasyprint works better than PrinceXML at least as far as that it looks the same but without the watermark, and that later one because it's actually open source. Before I tried wkhtmltopdf but that didn't work as well at all.

**Comment by olivertaylor** [comment]
I hadn't seen weasyprint before, thanks for the recommend.

The only thing that's prince-specific in textplay are two CSS rules. One tells has to do with not printing the page one page number, and the second tells prince to not create PDF bookmarks for all h1, h2, h3, etc.

If weasyprint has similar CSS rules I'd consider including them.

**Comment by LaPingvino** [comment]
Marking https://github.com/Kozea/WeasyPrint/issues/724 here for the first of the two, that doesn't seem to be supported yet. The bookmark-level css is supported exactly the same without prefix.

**Comment by LaPingvino** [comment]
https://github.com/Kozea/WeasyPrint/issues/474 < this seems to adequately solve the first page issue though :D. I am going to experiment a little and submit a Pull Request...
